ecomproject/cart/urls.py
from . import views
from django.urls import path
app_name='cart'
urlpatterns = [
    path('add/<int:product_id>/', views.add_cart, name='add_cart'),
    path('', views.cart_detail, name="cart_detail"),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('trash/<int:product_id>/', views.trash, name='trash'),
    ]

ecomproject/ecomapp/urls.py
from . import views
from django.urls import path
app_name='ecomapp'
urlpatterns = [

    path('', views.allprodCat, name="allprodCat"),
    path('<slug:c_slug>/',views.allprodCat , name='products_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/', views.proDetail, name='prodCatdetail'),

]

ecomproject/ecomproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ecomapp/', include("ecomapp.urls")),
    path('cart/', include('cart.urls')),
    path('search/', include('searchapp.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

ecomproject/searchapp/urls.py
from . import views
from django.urls import path
app_name='searchapp'
urlpatterns = [

    path('', views.SearchResult, name="SearchResult"),
]

ecomproject/cart/models.py
from django.db import models
from ecomapp.models import product

# Create your models here.
class Cart(models.Model):
    cart_id=models.CharField(max_length=250,blank=True)
    date_added=models.DateField(auto_now_add=True)

    class Meta:
        db_table='cart'
        ordering=['date_added']

    def __str__(self):
        return '{}'.format(self.cart_id)

class CartItem(models.Model):
    product=models.ForeignKey(product, on_delete=models.CASCADE)
    cart=models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity=models.IntegerField()
    active=models.BooleanField(default=True)

    class Meta:
        db_table='CartItem'

    def sub_total(self):
        return self.product.price * self.quantity

    def __str__(self):
        return '{}'.format(self.product)

ecomproject/ecomapp/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class category(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=25, unique=True)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='catagory', blank=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'catagory'
        verbose_name_plural = 'catagories'

    def get_url(self):
        return reverse('ecomapp:products_by_category', args=[self.slug])

    def __str__(self):
        return '{}'.format(self.name)


class product(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=205, unique=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    category = models.ForeignKey(category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='product', blank=True)
    stock = models.IntegerField()
    available = models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def get_url(self):
        return reverse('ecomapp:prodCatdetail', args=[self.category.slug, self.slug])

    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def __str__(self):
        return '{}'.format(self.name)

ecomproject/searchapp/models.py
from django.db import models

# Create your models here.

ecomproject/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from ecomapp.models import product
from .models import Cart, CartItem
from django.core.exceptions import ObjectDoesNotExist


# Create your views here.
def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart


def add_cart(request, product_id):
    prod = product.objects.get(id=product_id)
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(
            cart_id=_cart_id(request)
        )
        cart.save()
    try:
        cart_item = CartItem.objects.get(product=prod, cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity += 1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(
            product=prod,
            quantity=1,
            cart=cart
        )
        cart_item.save()
    return redirect('cart:cart_detail')


def cart_detail(request, total=0, counter=0, cart_items=None):
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart, active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request, 'cart.html', dict(cart_items=cart_items, total=total, counter=counter))


def cart_remove(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    prod = get_object_or_404(product, id=product_id)
    cart_item = CartItem.objects.get(product=prod, cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')


def trash(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    prod = get_object_or_404(product, id=product_id)
    cart_item = CartItem.objects.get(product=prod, cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail')

ecomproject/ecomapp/views.py
from django.shortcuts import render, get_object_or_404
from .models import category, product
from django.core.paginator import Paginator, EmptyPage, InvalidPage


# Create your views here.


def allprodCat(request, c_slug=None):
    c_page = None
    products_list = None
    if c_slug != None:
        c_page = get_object_or_404(category, slug=c_slug)
        products_list = product.objects.all().filter(category=c_page, available=True)
    else:
        products_list = product.objects.all().filter(available=True)
    paginator = Paginator(products_list, 6)
    try:
        page = int(request.GET.get('page', '1'))
    except:
        page = 1
    try:
        products = paginator.page(page)
    except (EmptyPage, InvalidPage):
        products = paginator.page(paginator.num_pages)
    return render(request, "category.html", {'category': c_page, 'products': products})


def proDetail(request, c_slug, product_slug):
    try:
        prod = product.objects.get(category__slug=c_slug, slug=product_slug)
    except Exception as e:
        raise e
    return render(request, 'product.html', {"product": prod})

ecomproject/searchapp/views.py
from django.shortcuts import render
from ecomapp.models import product
from django.db.models import Q
# Create your views here.
def SearchResult(request):
    products = None
    query = None
    if 'q' in request.GET:
        query = request.GET.get('q')
        products = product.objects.all().filter(Q(name__contains=query) | Q(description__contains=query))
        return render(request, 'search.html', {'query': query, 'products': products})

ecomproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
     <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" >
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>

    <meta name="description" content="{% block metadescription %} {% endblock %}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body><div class="container">
{% include 'header.html' %}
{% include 'navbar.html' %}
{% block content %}
{% endblock %}</div>
{% include 'footer.html' %}
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}" ></script>
</body>
</html>

ecomproject/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
          Add your Cart And Place The Order
{% endblock %}
{% block title %}
 Cart -ABC company pvt Ltd
{% endblock %}
{% block content %}
{% if not cart_items %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title"> Your shopping cart is empty</h1>
        <br>
        <p class="text-center">
            please click <a href="{% url 'ecomapp:allprodCat' %}">Here</a>to continue shopping
        </p>
    </div>
</div>
{% else %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">
            Your shopping Cart
        </h1>
        <br>
    </div>
</div>
<div class="row mx_auto">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my_custom_table">
            <thead class="my_custom_thead">
            <tr>
                <th colspan="5">
                    your items

                </th>
            </tr>
            </thead>
            <tbody>
            {% for cart_item in cart_items %}
            <tr>
                <td>
                    <a href="cart_item.product.get_absolute_url">
                        <img src="{{cart_item.product.image.url}}" alt="" style="width:100px;height:100px" class="float-left rounded custom_image"></a>

                </td>
                <td class="text-lef">
                    {{cart_item.product.name}}
                    <br><br>
                    SKU:{{cart_item.product.id}}
                    <br><br>
                    Price:$ {{cart_item.product.price}}
                    <br><br>
                    Qty:{{cart_item.quantity}} x $ {{cart_item}}
                </td>
                <td>
                    $ {{cart_item.sub_total}}
                </td>
                {% if cart_item.quantity < cart_item.product.stock %}
                <td>
                    <a href="{% url 'cart:add_cart' cart_item.product.id %} " class="custom_a">
                        <button>+</button></a>
                    &nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a" ><button>-</button></a>
                     &nbsp;<a href="{% url 'cart:trash' cart_item.product.id %}" class="custom_icon" ><button>TRASH</button></a>

                </td>
                {% else %}
                <td>

                    &nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a" ><button>-</button></a>
                    &nbsp;<a href="{% url 'cart:trash' cart_item.product.id %}" class="custom_icon" ><button>TRASH</button></a>

                </td>
                {% endif %}
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
<div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
    <table class="table my_custom_table">
        <thead class="my_custom_thead">
        <tr>
            <th>
                Checkout
            </th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>
                please review your shopping cart items before proceeding with the order payment.
            </td>
        </tr>
        <tr>
            <td class="text-left">
                your total is: <strong>{{ total }}</strong>

            </td>
        </tr>
        </tbody>
    </table><br><br>
    <div class="mx_auto">
        <a href="{% url 'ecomapp:allprodCat' %}" class="btn btn-secondary btn-block my_custom_button">
            continue shopping
        </a>
    </div>
</div>
</div>
{% endif %}
{% endblock %}

ecomproject/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
      {% if category %}
            {{ category.description|truncatewords:155 }}
      {% else %}
          Welcome to ABC stores where u can shop
      {% endif %}
{% endblock %}
{% block title %}
     {% if category %}
            {{ category.name }} -ABC stores
      {% else %}
          See our new collections _ABC stores
      {% endif %}
{% endblock %}
{% block content %}
     {% if category %}
           <div>
               <div class="row my_row_class">
                   <div class="mx-auto">
               <p><a href="{% url 'ecomapp:allprodCat' %}">Our product collections</a></p>
           </div></div>
           </div>
      {% endif %}
<div class="mx_auto">
    {% if category %}
   <center> <img src="{{category.image.url}}" alt="{{category.name}}" width="300" height="250"></center>
</div>
<br>
<div>
<h1 class="text-center my_title">{{category.name}}</h1>
<p class="text-justify">{{category.description}}</p></div>

   {% else %}
<div>
<img class="my_image my_image_padding" src="{% static 'img/banner.png' %}" alt="our products" width="1200" height="500"></div><br>
<div>
    <h1 class="text-center my_title">our product collections</h1>
    <p class="text-justify" ><h3>Shop with us and get gifts</h3></p></div>
{% endif %}
<div class="container">
    <div class="row mx_auto">
        {% for product in products.object_list %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-4">
            <div class="card text-center" style="min-width:18rem;">
                <a href="{{product.get_url}}"><img class="card-img-top my image" src="{{product.image.url}}" alt="{{product.name}}"></a>
                <div class="card-body">
                    <h4>{{product.name}}</h4>
                <p>{{product.price}}</p></div>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="mx_auto">
        {% if products.paginator.num_pages > 1 %}

   <hr>
        <div class="text-center">
            {% for pg in products.paginator.page_range %}
            <a href="?page={{pg}}" class="btn btn_light btn-sm {% if products.number == pg %} active {% endif %}">{{pg}}</a>
        {% endfor %}
        </div>
             {% endif %}
    </div>
    <br>
</div>
{% endblock %}

ecomproject/templates/footer.html
<div class="footer navbar-fixed-bottom my_footer">
    <p class="text-center">@copy; ABC tech pvt ltd.All rights Reserved</p>
</div>

ecomproject/templates/header.html
{% load static %}
<header>
  <center>
   <a href="{% url 'ecomapp:allprodCat' %}"> <img src="{% static 'img/logo.png' %}" alt="logimage"></a>
  </center>
</header>

ecomproject/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ecommerce</title>
</head>
<body>

</body>
</html>

ecomproject/templates/navbar.html
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <li class="nav-item">
          <a class="nav-link" href="#">Shop</a>
        </li>
        <li class="nav-item dropdown {% if 'ecomapp' in request.path %} active {% endif %}">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
           Categories
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'ecomapp:allprodCat' %}">All products</a></li>
            {% for category in links %}
            <li><a class="dropdown-item" href="{{category.get_url}}">{{category.name}}</a></li>
            {% endfor %}

          </ul>
        </li>
        {% if item_count > 0 %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'cart:cart_detail' %}"><button>CART
          ({{item_count}})</button></a>
        </li>
        {% endif %}
      </ul>
      <form class="d-flex" action="{% url 'searchapp:SearchResult' %}" method="get">
        {% csrf_token %}
        <input class="form-control me-2" type="search" placeholder="Search" name="q" aria-label="Search">
        <button class="btn btn-outline-success" type="submit"><i class="fa fa-search"></i></button>
      </form>
    </div>
  </div>
</nav>

ecomproject/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

       {{product.description|truncatewords:155}}
{% endblock %}

{% block title %}
  {% if category %}
     {{ product.name }} --ABC stores
{% endif %}
{% endblock %}

{% block content %}
<div class="row my_prod_row_class">
    <div class="mx_auto">
    <p><a href="{% url 'ecomapp:allprodCat' %}">Home</a> | <a href="{{product.category.get_url}}">{{product.category}}</a>|{{product.name}}</p>
</div>
</div>
<div class="container">
<br>
<div class="row">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <div style="min-width:18rem">
        <img src="{{product.image.url}}" alt="{{product.name}}" width="250px" height="250px">
    </div></div></div>
</div>
<div>
    <div class="col-12 col-sm-12 col-md-12 col-lg-6">
        <div>
        <h1 class="my_prod_title">{{product.name}}</h1>
        <p><h3>$ {{product.price}}</h3></p>
        <p><h3>PRODUCT DESCRIPTION</h3></p>
        <p class="text-justify my_prod_text">{{product.description}}</p>
        {% if product.stock <= 0 %}
        <p class="text-justify my_prod_text"><b>out of stock</b></p>
        {% else %}
        <a class="btn btn_secondary" href="{% url 'cart:add_cart' product.id %}">Add to cart</a>
        {% endif %}


    </div></div>
</div>
{% endblock %}

ecomproject/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
          we have variety of baby clothes and unique kids wear.
{% endblock %}
{% block title %}
  search
{% endblock %}
{% block content %}
  <div>
      <p class="text-center my_search_text">You have searched for <b>"{{query}}"</b></p>
  </div>
<div class="container">
    <div class="row mx_auto">
        {% for product in products %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-4">
            <div class="card text-center" style="min-width:18rem;">
                <a href="{{product.get_url}}"><img class="card-img-top my image" src="{{product.image.url}}" alt="{{product.name}}"></a>
                <div class="card-body">
                    <h4>{{product.name}}</h4>
                <p>{{product.price}}</p>
                </div>
            </div>
        </div>

    {% empty %}
    <div class="row mx-auto">
        <p class="text-center my_search_text">0 results found</p>
    </div>
    {% endfor %}
</div>
</div>
{% endblock %}